<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataModel\Device.cs" />
    <Compile Remove="DataModel\Note.cs" />
    <Compile Remove="DeviceDiscoveryService.cs" />
    <Compile Remove="Services\MqttService.cs" />
  </ItemGroup>

</Project>
